config/routes.rb
Rails.application.routes.draw do
  resources :ratings

  resources :participations

  resources :users

  resources :rooms

  root 'rooms#index'

end

app/models/participation.rb
class Participation < ActiveRecord::Base
  belongs_to :user
  belongs_to :room
end

app/models/rating.rb
class Rating < ActiveRecord::Base
  belongs_to :user
  belongs_to :room
end

app/models/room.rb
class Room < ActiveRecord::Base
  has_many :participations
  has_many :users, :through => :participations
  has_many :ratings

  validates :name, :presence => true

  scope :stale, lambda { where("rooms.created_at < ?", 2.days.ago) }

  def average_score
    ratings = self.class.find_by_sql([
      "SELECT t1.score
      FROM ratings AS t1
      LEFT OUTER JOIN ratings AS t2
      ON t1.user_id = t2.user_id
      AND (t1.created_at < t2.created_at
         OR (t1.created_at = t2.created_at AND t1.id < t2.id))
      WHERE t2.user_id IS NULL
      AND t1.user_id IN (?)
      AND t1.room_id = ? ", users.pluck(:id), self.id])

    return nil if ratings.empty?
    ratings.map(&:score).sum.to_f/ratings.length
  end

  def self.average_scores
    Hash[*Room.all.map {|room| [room.id, room.average_score]}.flatten]
  end

  def self.summary
    Hash[*Room.all.map { |room|
           [room.id, {avgScore: room.average_score, participants: room.users.count}]
         }.flatten]
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  belongs_to :user
  belongs_to :room
  has_many :participations, :dependent => :destroy
  has_many :rooms, :through => :participations
  has_many :ratings, :dependent => :destroy

  def in_room?(room)
    rooms.include?(room)
  end

  def rate(room, score)
    Rating.new(user: self, room: room, score: score).save!
  end

  def last_rating_for(room)
    ratings.where(room: room).order(created_at: :desc).first
  end

  def participation_for(room)
    participations.where(room: room).order(created_at: :desc).first
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    return unless session[:user_id]
    @current_user ||= User.find(session[:user_id])
  end
  helper_method :current_user

  def logged_in?
    current_user.present?
  end
  helper_method :logged_in?

  def ws_scheme
    ENV['RACK_ENV'] == "production" ? "wss://" : "ws://"
  end
  helper_method :ws_scheme
end

app/controllers/participations_controller.rb
class ParticipationsController < ApplicationController

  def create
    participation = Participation.new(participation_params)
    participation.user = current_user
    if participation.save
      redirect_to room_path(participation.room)
    else
      redirect_to room_path(participation.room)
    end
    Clients.push_room_data
  end

  def destroy
    participation = Participation.find(params[:id])
    participation.destroy
    redirect_to room_path(participation.room)
    Clients.push_room_data
  end

  def participation_params
    params.require(:participation).permit(:room_id)
  end

end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController

  def create
    @rating = Rating.new(rating_params)
    @rating.user = current_user
    if @rating.save
      redirect_to @rating.room
    else
      redirect_to @rating.room
    end
    Clients.push_room_data
  end

  def rating_params
    params.require(:rating).permit(:name, :score, :room_id)
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: [:show, :edit, :update, :destroy]

  # GET /rooms
  # GET /rooms.json
  def index
    @rooms = Room.order(created_at: :desc)
  end

  # GET /rooms/1
  # GET /rooms/1.json
  def show
    @rating = current_user.try(:last_rating_for, @room).try(:dup)
    @participation = current_user.try(:participation_for, @room) || Participation.new(room: @room)
  end

  # GET /rooms/new
  def new
    @room = Room.new
  end

  # GET /rooms/1/edit
  def edit
  end

  # POST /rooms
  # POST /rooms.json
  def create
    @room = Room.new(room_params)

    respond_to do |format|
      if @room.save
        format.html { redirect_to @room, notice: 'Room was successfully created.' }
        format.json { render :show, status: :created, location: @room }
      else
        format.html { render :new }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rooms/1
  # PATCH/PUT /rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to @room, notice: 'Room was successfully updated.' }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1
  # DELETE /rooms/1.json
  def destroy
    @room.destroy
    respond_to do |format|
      format.html { redirect_to rooms_url, notice: 'Room was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
  def set_room
    @room = Room.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def room_params
    params.require(:room).permit(:name)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        # A user == session, since there is nothing to persist
        session[:user_id] = @user.id
        format.html { redirect_to rooms_path, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    # User == session for right now
    session[:user_id] = nil
    respond_to do |format|
      format.html { redirect_to rooms_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper

  def options_for_rating
    (1..5).map { |x| [x,x]}
  end

  def average_score(room)
    if room.average_score
      "%.2f" % room.average_score
    else
      "none"
    end
  end

  def default_rating(rating, room)
    rating || Rating.new(room: room, score: 3)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Speakup</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="navbar navbar-default navbar-top">
  <div class="container">
    <div class="navbar-header">
      <%= link_to "SpeakUp", root_path, class: "navbar-brand" %>
      <button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#navbar-main">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div class="navbar-collapse collapse" id="navbar-main">
      <ul class="nav navbar-nav">
        <li>
          <%= link_to 'Lobby', rooms_path %>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if current_user %>
          <%= form_for current_user, html: {class: "navbar-form", method: 'delete'} do |f| %>
            <%= f.hidden_field :name %>
            <%= f.button 'Log out', class: "btn btn-default navbar-btn" %>
          <% end %>
        <% else %>
          <%= form_for User.new, html: {class: "navbar-form"} do |f| %>
            <%= f.hidden_field :name %>
            <%= f.button 'Log in', class: "btn btn-default navbar-btn" %>
          <% end %>
        <% end %>
      </ul>
    </div>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col-lg-12">
      <div class="alert alert-danger" role="alert" id="unsupported-browser" style="display:none">
        SpeakUp does not support your browser.
      </div>
      <script>
       $(document).ready(function() {
         if (!Modernizr.websockets) {
           $('#unsupported-browser').show();
          }
       });
      </script>
    </div>
    <div class="col-lg-12">
      <%= yield %>
    </div>
  </div>
</div>
</body>
</html>

app/views/rooms/_form.html.erb
<div class="well col-lg-12">
<%= form_for(@room, html: {class: "form-horizontal"}) do |f| %>
  <fieldset>
    <% if @room.errors.any? %>
    <div class="text-danger">
      <h4><%= pluralize(@room.errors.count, "error") %> prohibited this room from being saved:</h4>

      <ul>
        <% @room.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
      </ul>
    </div>
    <% end %>

    <div class="form-group">
      <%= f.label :name, class: "col-lg-1 control-label" %>
      <div class="col-lg-11">
        <%= f.text_field :name, class: "form-control" %>
      </div>
    </div>
    <div class="form-group">
      <div class="col-lg-10 col-lg-offset-1">
        <%= f.submit class: "btn btn-primary" %>
        <%= link_to 'Cancel', rooms_path, :class => 'btn btn-default' %>
      </div>
    </div>
  </fieldset>
<% end %>
</div>

app/views/rooms/edit.html.erb
<h1>Editing room</h1>

<%= render 'form' %>

<%= link_to 'Show', @room %> |
<%= link_to 'Back', rooms_path %>

app/views/rooms/index.html.erb
<div class="page-header">
  <h1>
  Lobby
  </h1>
</div>

<h3>Rooms</h3>
<ul class="list-group">
  <% @rooms.each do |room| %>
    <li class="list-group-item">
      <span class="badge"><%= room.users.count %></span>
      <%= link_to room.name, room %>
      <em>(created <%= room.created_at.strftime "%Y-%m-%d" %>)</em>
    </li>
  <% end %>
</ul>

<% if logged_in? %>
  <%= link_to 'New Room', new_room_path, :class => "btn btn-primary" %>
<% end %>

app/views/rooms/new.html.erb
<div class="page-header">
  <h1>New room</h1>
</div>

<%= render 'form' %>

app/views/rooms/show.html.erb
<div class="page-header">
  <h1><%= @room.name %></h1>
</div>

<div class="col-lg-3">
  <div class="panel panel-primary">
    <div class="panel-heading clearfix">
      <h3 class="panel-title pull-left">Participants</h3>
      <button type="button"
        class="btn btn-sm btn-info pull-right"
        data-toggle="popover"
        data-placement="bottom"
        data-html="true"
        data-container="body"
        data-content="<p>If you are attending a meeting remotely, join the room to give feedback on the meeting volume.</p><p>The meeting organizer does not need to join the room.</p>">
        ?
      </button>
    </div>
    <div class="panel-body" id="participants-panel">
       <div id="participants"></div>
       <% if logged_in? %>
         <% if current_user.in_room?(@room) %>
           <%= button_to 'Leave room', participation_path(@participation), :method => 'delete', :class => "btn btn-warning" %>
         <% else %>
           <%= form_for @participation do |f| %>
             <%= f.hidden_field :room_id %>
             <%= f.button 'Join room', class: "btn btn-primary" %>
           <% end %>
         <% end %>
       <% else %>
         <p>(Log in to join room)</p>
       <% end %>
      </div>
  </div>
</div>


<div id="room-panels"/>

<script>
  $(document).ready(function() {
    var scheme   = "<%= ws_scheme %>";
    var room_id = "<%= @room.id%>";
    var initialAvgScore = <%= @room.average_score || "null" %>;
    var initialUserScore = <%= default_rating(@rating, @room).score || "null" %>;
    var canSubmitScore = <%= logged_in? && current_user.in_room?(@room) %>
    window.AUTHENTICITY_TOKEN = "<%= form_authenticity_token %>";

    React.renderComponent(
      Speakup.Components.ParticipantCount({uri: wsUri(scheme),
                                           roomId: room_id,
                                           initialParticipants: <%= @room.users.size %>}),
      document.getElementById('participants'));
    React.renderComponent(
      Speakup.Components.Room({uri: wsUri(scheme),
                               initialUserScore: initialUserScore,
                               initialAvgScore: initialAvgScore,
                               canSubmitScore: canSubmitScore,
                               roomId: room_id}),
      document.getElementById('room-panels'));
  });
</script>
<script>
  $("button[data-toggle=popover]").popover();
</script>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>